'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TouchTest.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1266721() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1266721", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _1455554377_line_10_icon_icons_com_53304() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1455554377_line_10_icon_icons_com_53304", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1455554377_line_10_icon_icons_com_533041() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1455554377_line_10_icon_icons_com_533041", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2920659_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2920659_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _30_Text_256x256_35366() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_30_Text_256x256_35366", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _30_Text_256x256_353661() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_30_Text_256x256_353661", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _3643769_building_home_house_main_menu_start_113416() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_3643769_building_home_house_main_menu_start_113416", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3643769_building_home_house_main_menu_start_1134161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3643769_building_home_house_main_menu_start_1134161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_local_grocery_store_128_28460() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_local_grocery_store_128_28460", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_local_grocery_store_128_284601() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_local_grocery_store_128_284601", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property internet_world_wide_web_www_globe_communication_website_browser_network_connection_icon_195710() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("internet_world_wide_web_www_globe_communication_website_browser_network_connectio"& _ 
                        "n_icon_195710", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property internet_world_wide_web_www_globe_communication_website_browser_network_connection_icon_1957101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet_world_wide_web_www_globe_communication_website_browser_network_connectio"& _ 
                        "n_icon_1957101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logout_90894() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout_90894", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property logout_908941() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("logout_908941", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minimize2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Not_Done_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Not_Done_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picture_file_image_photo_gallery_icon_219527() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picture_file_image_photo_gallery_icon_219527", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property picture_file_image_photo_gallery_icon_2195271() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("picture_file_image_photo_gallery_icon_2195271", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property PixelKit_Shape_193_copy_37747() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PixelKit_Shape_193_copy_37747", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PixelKit_Shape_193_copy_377471() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PixelKit_Shape_193_copy_377471", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property profile_picture_user_icon_153847() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("profile_picture_user_icon_153847", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property profile_picture_user_icon_1538471() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("profile_picture_user_icon_1538471", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restart_icon_227406() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restart_icon_227406", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property restart_icon_2274061() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("restart_icon_2274061", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Search_find_locate_1542() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Search_find_locate_1542", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Search_find_locate_15421() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search_find_locate_15421", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property settings_online_web_pc_mac_monitor_icon_icons_com_59975() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_online_web_pc_mac_monitor_icon_icons_com_59975", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_online_web_pc_mac_monitor_icon_icons_com_599751() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_online_web_pc_mac_monitor_icon_icons_com_599751", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property task_manager_18854() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("task_manager_18854", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property task_manager_188541() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("task_manager_188541", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property TryOS_USW() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("TryOS_USW", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
